/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.pos.gudang.Panel;

import id.ac.pos.gudang.DAO.KirimanDAO;
import id.ac.pos.gudang.DAOImpl.KirimanDAOImpl;
import id.ac.pos.gudang.Dialog.DialogTambahMaterai;
import id.ac.pos.gudang.Dialog.DialogTambahSampul;
import id.ac.pos.gudang.Frame.FrameUtama;
import id.ac.pos.gudang.TabelModel.KirimanTM;
import id.ac.pos.gudang.entity.Kiriman;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author reyhanadp
 */
public class PanelIsiKiriman extends javax.swing.JPanel {

    String jenis;
    TableRowSorter sorter;
    KirimanDAO kirimanDAO = new KirimanDAOImpl();
    /**
     * Creates new form panelIsi
     */
    public PanelIsiKiriman() {

    }

    PanelIsiKiriman(String jenis) {
        initComponents();
        
        this.jenis = jenis;
        if(jenis.equals("MTR")){
            ArrayList<Kiriman> Array_kiriman = kirimanDAO.tampilTabel(this.jenis);
                
            KirimanTM kirimanTM = new KirimanTM();
            kirimanTM.setDataKiriman(Array_kiriman);
            sorter = new TableRowSorter(kirimanTM);
            tabelKiriman.setRowSorter(sorter);
            tabelKiriman.setModel(kirimanTM);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKiriman = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Kiriman Produk"));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelKiriman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKiriman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.jenis == "MTR") {
            FrameUtama frameUtama = new FrameUtama();
            DialogTambahMaterai dialogTambahMaterai = new DialogTambahMaterai(frameUtama, true, this.jenis);
            dialogTambahMaterai.setVisible(true);
        } else {
            FrameUtama frameUtama = new FrameUtama();
            DialogTambahSampul dialogTambahSampul = new DialogTambahSampul(frameUtama, true, this.jenis);
            dialogTambahSampul.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKiriman;
    // End of variables declaration//GEN-END:variables
}
