/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.pos.gudang.Panel;

import java.awt.CardLayout;

/**
 *
 * @author Firman
 */
public class PanelKiriman extends javax.swing.JPanel {

    /**
     * Creates new form panelKiriman
     */
    public PanelKiriman() {
        initComponents();
        Materai.removeAll();
        Materai.repaint();
        Materai.revalidate();
        CardLayout cardLayout = (CardLayout) Materai.getLayout();
        String jenis = "MTR";
        PanelIsiKiriman isiKiriman = new PanelIsiKiriman(jenis);
        Materai.add("Panel Pemesanan", isiKiriman);
        Materai.repaint();
        Materai.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneKiriman = new javax.swing.JTabbedPane();
        Materai = new javax.swing.JPanel();
        Sampul = new javax.swing.JPanel();

        tabbedPaneKiriman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbedPaneKirimanMouseClicked(evt);
            }
        });

        Materai.setLayout(new java.awt.CardLayout());
        tabbedPaneKiriman.addTab("Materai", Materai);

        Sampul.setLayout(new java.awt.CardLayout());
        tabbedPaneKiriman.addTab("Sampul", Sampul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneKiriman)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneKiriman, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabbedPaneKirimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbedPaneKirimanMouseClicked
        // TODO add your handling code here:
        String jenis;
        if (tabbedPaneKiriman.getSelectedIndex() == 0) {
            Materai.removeAll();
            Materai.repaint();
            Materai.revalidate();
            CardLayout cardLayout = (CardLayout) Materai.getLayout();
            jenis = "MTR";
            PanelIsiKiriman isiKiriman = new PanelIsiKiriman(jenis);
            Materai.add("Panel Pemesanan", isiKiriman);
            Materai.repaint();
            Materai.revalidate();
        } else if (tabbedPaneKiriman.getSelectedIndex() == 1) {
            Sampul.removeAll();
            Sampul.repaint();
            Sampul.revalidate();
            CardLayout cardLayout = (CardLayout) Sampul.getLayout();
            jenis = "SMP";
            PanelIsiKiriman isiKiriman = new PanelIsiKiriman(jenis);
            Sampul.add("Panel Pemesanan", isiKiriman);
            Sampul.repaint();
            Sampul.revalidate();
        }
    }//GEN-LAST:event_tabbedPaneKirimanMouseClicked

    private void TabPengembalianMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Materai;
    private javax.swing.JPanel Sampul;
    private javax.swing.JTabbedPane tabbedPaneKiriman;
    // End of variables declaration//GEN-END:variables
}
