/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.pos.gudang.Panel;

import java.awt.CardLayout;

/**
 *
 * @author reyhanadp
 */
public class panelContoh extends javax.swing.JPanel {

    /**
     * Creates new form panelContoh
     */
    public panelContoh() {
        initComponents();
        Prangko2.removeAll();
        Prangko2.repaint();
        Prangko2.revalidate();
        CardLayout cardLayout = (CardLayout) Prangko2.getLayout();
        panelIsi contoh = new panelIsi();
        Prangko2.add("Panel Pemesanan", contoh);
        Prangko2.repaint();
        Prangko2.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPengembalian = new javax.swing.JTabbedPane();
        Prangko2 = new javax.swing.JPanel();
        MS_SS2 = new javax.swing.JPanel();
        SHP_SHPSS2 = new javax.swing.JPanel();
        Kemasan2 = new javax.swing.JPanel();
        Merchandise2 = new javax.swing.JPanel();
        Prisma2 = new javax.swing.JPanel();
        DokumenFilateli2 = new javax.swing.JPanel();

        TabPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPengembalianMouseClicked(evt);
            }
        });

        Prangko2.setLayout(new java.awt.CardLayout());
        TabPengembalian.addTab("Prangko", Prangko2);

        javax.swing.GroupLayout MS_SS2Layout = new javax.swing.GroupLayout(MS_SS2);
        MS_SS2.setLayout(MS_SS2Layout);
        MS_SS2Layout.setHorizontalGroup(
            MS_SS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        MS_SS2Layout.setVerticalGroup(
            MS_SS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        TabPengembalian.addTab("MS & SS", MS_SS2);

        javax.swing.GroupLayout SHP_SHPSS2Layout = new javax.swing.GroupLayout(SHP_SHPSS2);
        SHP_SHPSS2.setLayout(SHP_SHPSS2Layout);
        SHP_SHPSS2Layout.setHorizontalGroup(
            SHP_SHPSS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        SHP_SHPSS2Layout.setVerticalGroup(
            SHP_SHPSS2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        TabPengembalian.addTab("SHP & SHPSS", SHP_SHPSS2);

        javax.swing.GroupLayout Kemasan2Layout = new javax.swing.GroupLayout(Kemasan2);
        Kemasan2.setLayout(Kemasan2Layout);
        Kemasan2Layout.setHorizontalGroup(
            Kemasan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        Kemasan2Layout.setVerticalGroup(
            Kemasan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        TabPengembalian.addTab("Kemasan", Kemasan2);

        javax.swing.GroupLayout Merchandise2Layout = new javax.swing.GroupLayout(Merchandise2);
        Merchandise2.setLayout(Merchandise2Layout);
        Merchandise2Layout.setHorizontalGroup(
            Merchandise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        Merchandise2Layout.setVerticalGroup(
            Merchandise2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        TabPengembalian.addTab("Merchandise", Merchandise2);

        javax.swing.GroupLayout Prisma2Layout = new javax.swing.GroupLayout(Prisma2);
        Prisma2.setLayout(Prisma2Layout);
        Prisma2Layout.setHorizontalGroup(
            Prisma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        Prisma2Layout.setVerticalGroup(
            Prisma2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        TabPengembalian.addTab("Prisma", Prisma2);

        javax.swing.GroupLayout DokumenFilateli2Layout = new javax.swing.GroupLayout(DokumenFilateli2);
        DokumenFilateli2.setLayout(DokumenFilateli2Layout);
        DokumenFilateli2Layout.setHorizontalGroup(
            DokumenFilateli2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        DokumenFilateli2Layout.setVerticalGroup(
            DokumenFilateli2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        TabPengembalian.addTab("Dokumen Filateli", DokumenFilateli2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPengembalian)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPengembalian, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TabPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPengembalianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabPengembalianMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DokumenFilateli2;
    private javax.swing.JPanel Kemasan2;
    private javax.swing.JPanel MS_SS2;
    private javax.swing.JPanel Merchandise2;
    private javax.swing.JPanel Prangko2;
    private javax.swing.JPanel Prisma2;
    private javax.swing.JPanel SHP_SHPSS2;
    private javax.swing.JTabbedPane TabPengembalian;
    // End of variables declaration//GEN-END:variables
}
