/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.pos.gudang.Frame;

import id.ac.pos.gudang.Dialog.DialogLaporan;
import id.ac.pos.gudang.Panel.PanelIsiKiriman;
import id.ac.pos.gudang.Panel.PanelKiriman;
import id.ac.pos.gudang.Panel.PanelProduk;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author reyhanadp
 */
public class FrameUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Materai.removeAll();
        Materai.repaint();
        Materai.revalidate();
        CardLayout cardLayout = (CardLayout) Materai.getLayout();
        PanelProduk produk = new PanelProduk("MTR");
        Materai.add("Panel Pemesanan", produk);
        Materai.repaint();
        Materai.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        buttonKelolaProduk = new javax.swing.JButton();
        buttonLaporan = new javax.swing.JButton();
        buttonKiriman = new javax.swing.JButton();
        panelUtama = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tabbedPaneProduk = new javax.swing.JTabbedPane();
        Materai = new javax.swing.JPanel();
        Sampul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonKelolaProduk.setText("KELOLA PRODUK");
        buttonKelolaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelolaProdukActionPerformed(evt);
            }
        });

        buttonLaporan.setText("LAPORAN");
        buttonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanActionPerformed(evt);
            }
        });

        buttonKiriman.setText("KIRIMAN");
        buttonKiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKirimanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonKelolaProduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonKiriman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonKelolaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonKiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panelUtama.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        tabbedPaneProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbedPaneProdukMouseClicked(evt);
            }
        });

        Materai.setLayout(new java.awt.CardLayout());
        tabbedPaneProduk.addTab("Materai", Materai);

        Sampul.setLayout(new java.awt.CardLayout());
        tabbedPaneProduk.addTab("Sampul", Sampul);

        jPanel2.add(tabbedPaneProduk, "card2");

        panelUtama.add(jPanel2, "card2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pos_indonesia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLaporanActionPerformed

    private void buttonKelolaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelolaProdukActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        panelUtama.revalidate();
        panelUtama.add(jPanel2);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_buttonKelolaProdukActionPerformed

    private void buttonKirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKirimanActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        panelUtama.revalidate();
        CardLayout cardLayout = (CardLayout) panelUtama.getLayout();
        PanelKiriman panelkiriman = new PanelKiriman();
        panelUtama.add("Panel Kiriman", panelkiriman);
        panelUtama.repaint();
        panelUtama.revalidate();
    }//GEN-LAST:event_buttonKirimanActionPerformed

    private void tabbedPaneProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbedPaneProdukMouseClicked
        // TODO add your handling code here:
        String jenis;
        if (tabbedPaneProduk.getSelectedIndex() == 0) {
            Materai.removeAll();
            Materai.repaint();
            Materai.revalidate();
            CardLayout cardLayout = (CardLayout) Materai.getLayout();
            jenis= "MTR";
            PanelProduk produk = new PanelProduk(jenis);
            Materai.add("Panel Pemesanan", produk);
            Materai.repaint();
            Materai.revalidate();
        } else if (tabbedPaneProduk.getSelectedIndex() == 1) {
            Sampul.removeAll();
            Sampul.repaint();
            Sampul.revalidate();
            CardLayout cardLayout = (CardLayout) Sampul.getLayout();
            jenis = "SMP";
            PanelProduk produk = new PanelProduk(jenis);
            Sampul.add("Panel Pemesanan", produk);
            Sampul.repaint();
            Sampul.revalidate();
        }
    }//GEN-LAST:event_tabbedPaneProdukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            com.jtattoo.plaf.noire.NoireLookAndFeel.setTheme("Large-Font", "Java Swing", "");
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Materai;
    private javax.swing.JPanel Sampul;
    private javax.swing.JButton buttonKelolaProduk;
    private javax.swing.JButton buttonKiriman;
    private javax.swing.JButton buttonLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTabbedPane tabbedPaneProduk;
    // End of variables declaration//GEN-END:variables
}
